### ISSUE TITLE
Landscape orientation difficult

### ISSUE THREAD

**Issue by matty337s** [makstron/TCharts#2]
The chart doesn't sit well in landscape orientation, possibly due to a fixed height? It will always stick out the bottom of a container or cut off the navigation view.

**Comment by makstron** [comment]
Hi. Can you send me .xml with an example?

**Comment by matty337s** [comment]
I have attached a (very) basic .xml that should show the issue. I have however tried it many different ways, directly in ConstraintLayout, in LinearLayout, and using all types of layout_width and layout_height attributes (match_parent, match_constraint, fixed value). The only way I can get it working correctly is in a scrollview, but this is definitely not an ideal solution.  Padding the sides (image 2) does what you'd expect, however padding top and bottom (image 3) either crops or shifts the chart down. Setting layout_height to wrap_content (image 4) centres the chart enough to see part of the NavigationView, but would likely not work on all devices. 
P.S. Apologies if I am not providing the correct information here, or it is a simple error of mine, I am a university student without a great deal of Android experience, but keen to learn.






```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.klim.tcharts.TChart
        android:id="@+id/tchart"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="16dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```


![thumbnail_1619608930354](https://user-images.githubusercontent.com/18316941/116396119-144c8380-a879-11eb-827b-90045424cf96.jpg)
![thumbnail_1619608930346](https://user-images.githubusercontent.com/18316941/116396131-16aedd80-a879-11eb-9d37-045da141af60.jpg)
![thumbnail_1619608930337](https://user-images.githubusercontent.com/18316941/116396128-16164700-a879-11eb-8d8e-03f970304fe5.jpg)
![thumbnail_1619608930327](https://user-images.githubusercontent.com/18316941/116396126-157db080-a879-11eb-848f-eecf01b78196.jpg)

**Comment by makstron** [comment]
Sorry, I was on vacation. This chart really has problems with padding but what do you want to get when set padding?

**Comment by matty337s** [comment]
I get the same issues when I set padding. The issue was solved however, when I included TCharts as a Java Module into my app rather than adding through gradle. Don't ask me why! I'll mark it as closed, as it seems to be working now.
