### ISSUE TITLE
Any plans for a Java example

### ISSUE THREAD

**Issue by KJH1964** [makstron/TCharts#3]
Hi,

Live the look of the component, and particularly that the values on the x-axis are actually Dates/Times, but I'm relatively new to Java, and have never used Kotlin, and I'd love to try it out. I suspect I can probably hack it but if you are planning to release a Java example tomorrow I'd be better off waiting.

Thanks

**Comment by KJH1964** [comment]
Digging deeper the TCharts component is in Java so I should be able to create my own example.
Cheers

**Comment by KJH1964** [comment]
Digging deeper the TCharts element is in Java, so I should be able to figure it out,
Cheers

**Comment by makstron** [comment]
README.md contains a java example. Or I did not understand what do you want.
Do you want MainActivity on java?

**Comment by KJH1964** [comment]
Thanks, I’ll take a look at readme, typical dev need to RTFM, 😉

**Comment by makstron** [comment]
KJH1964, did you find a solution to your problem?
